PERF-3398 Extend dotted path projection microbenchmarks
mongodb/mongo-perf pull request #106
Opened 2022-10-14 20:09 UTC by mtandrei

evergreen: 
https://spruce.mongodb.com/version/6349c10032f4177f4d07becc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

2022-10-14 20:14 UTC, mtandrei commented on testcases/simple_query.js
> -        name: "PointQuery_MultipleIndexes_LL",
clion keeps doing this and I don't know why. I'm cool with deleting these extraneous spaces, but if you don't want noise in the PR, I can try removing this.

2022-10-14 20:14 UTC, mtandrei commented on testcases/simple_query.js
> +                    {d: {e: [{f: i, g: i}, {f: i, g: i}, {f: i, g: i}, {f: i, g: i}, {f: i, g: i}]}},
open to suggestions for how many elements we should have in each array

2022-10-14 20:14 UTC, mtandrei commented on testcases/simple_query.js
> +    addTestCase({
If you'd like, I can try and factor these into a for loop

2022-10-17 18:33 UTC, dstorch commented
After discussing with Mihai, we think @leozzx can be responsible for doing the code review for this patch. I'm removing myself from the reviewers list.

2022-10-17 20:48 UTC, leozzx requested changes
Some minor suggestions.

2022-10-17 20:48 UTC, leozzx commented on testcases/simple_query.js
> +    addTestCase({
This is fine to me, but would it be better to have a function to add both inclusion and exclusion test cases in it?

2022-10-17 20:48 UTC, leozzx commented on testcases/simple_query.js
> +                    {d: {e: [{f: i, g: i}, {f: i, g: i}, {f: i, g: i}, {f: i, g: i}, {f: i, g: i}]}},
size of 5 is fine to me, does it make sense to also have test cases for array with size 1?

2022-10-17 20:48 UTC, leozzx commented on testcases/simple_query.js
> +        // Adding a views passthrough would be redundant.
is `Aggregation.xxx` also redundant?

2022-10-17 20:48 UTC, leozzx commented on testcases/simple_query.js
> +                {b: [{c: i, d: i}, {c: i, d: i}, {c: i, d: i}, {c: i, d: i}, {c: i, d: i}]}]};
I assume `i` here is integer, should we also test non numeric type, e.g. object, string, array?

2022-10-17 20:48 UTC, leozzx commented on testcases/simple_query.js
> +        op: {op: "find", query: {}, filter: {b: 1, c: 1, d: 1, e: 1, f: 1, g: 1, h: 1, i: 1, j: 1}}
do you want to exclude `_id`? I see you always do that in above test cases.

2022-10-17 20:48 UTC, leozzx commented on testcases/simple_query.js
> +
Not related to this PR, I think we should break down this file into multiple ones, this file has 1,200+ lines and we are adding more workloads, this is too much for a single file.

2022-10-17 20:48 UTC, leozzx commented on testcases/simple_query.js
> +        op: {op: "find", query: {}, filter: {b: 0, c: 0, d: 0, e: 0, f: 0, g: 0, h: 0, i: 0, j: 0}}
This is not related to "dotted path projection", did you find this is missing in existing workloads?

2022-10-18 17:40 UTC, mtandrei reviewed
Thanks for the comments Zixuan! I've responded to them in the latest commit.

2022-10-18 17:48 UTC, leozzx commented on testcases/simple_query.js
> +                    {d: {e: [{f: i, g: i}, {f: i, g: i}, {f: i, g: i}, {f: i, g: i}, {f: i, g: i}]}},
Comparing to scalar, single element array workload can tell how we perform differently for handling array case.
And comparing to array of size 5, it can tell how the performance is with the scale of array size.

2022-10-18 18:10 UTC, leozzx requested changes
One open discussion and a minor suggestion.

2022-10-18 18:10 UTC, leozzx commented on testcases/simple_query.js
> +    addInclusionExclusionTestCase("WideProjectionNestedField", nestedWideProjectionDocGenerator, {_id: 0, n: {b: 1, c: 1, d: 1, e: 1, f: 1, g: 1, h: 1, i: 1, j: 1}}, {_id: 1, n: {b: 0, c: 0, d: 0, e:
is this line too long?
```suggestion
    addInclusionExclusionTestCase("WideProjectionNestedField" /* name */, 
                                                           nestedWideProjectionDocGenerator, 
                                                           {_id: 0, n: {b: 1, c: 1, d: 1, e: 1, f: 1, g: 1, h: 1, i: 1, j: 1}} /* inclusionSpec */, 
                                                           {_id: 1, n: {b: 0, c: 0, d: 0, e: 0, f: 0, g: 0, h: 0, i: 0, j: 0}} /* exclusionSpec */);
```

2022-10-18 21:30 UTC, mtandrei reviewed
Thanks for taking another look Zixuan! Updated the outstanding feedback

2022-10-18 23:01 UTC, leozzx approved these changes
Thanks for addressing my comments.

2022-10-19 14:27 UTC, mtandrei commented
Thanks for the review Zixuan!

2022-10-19 14:27 UTC, merged