Added a note to explain 6.0 change to mongosh
mongodb/mongo-perf pull request #113
Opened 2022-11-03 19:47 UTC by ghartnett

2022-11-03 20:35 UTC, dalyd approved these changes
Probably worth a couple more words on how to download the correct thing, but otherwise LGTM.

2022-11-03 20:35 UTC, dalyd commented on README.md
> +Since 6.0, the legacy "mongo" shell has been replaced with "mongosh" which does not support benchRun(). To run this micro benchmark with MongoDB 6.0 you'll also need to download the 5.0 legacy "mongo
Should we include some instructions on how to download the legacy shell?

2022-11-03 23:01 UTC, dstorch requested changes
Thanks for picking this up @ghartnett! I had it on my list to file a ticket about this, but you beat me to the punch 😄 .

I'm curious what you think about the comment I left.

2022-11-03 23:01 UTC, dstorch commented on README.md
> +Since 6.0, the legacy "mongo" shell has been replaced with "mongosh" which does not support benchRun(). To run this micro benchmark with MongoDB 6.0 you'll also need to download the 5.0 legacy "mongo
I'm not sure that we should document it this way. My vote would be to take an even stronger stance and say that this tool is not user-facing or supported whatsoever for external users by MongoDB. We should make it clear that it's "use at your own risk".

That said, if we do make it clear that we're not supporting this project for external use, then it seems fine to include the hint about the "choose your own adventure" path that involves downloading the 5.0 shell.

2022-11-22 15:46 UTC, dstorch commented
@ghartnett what's the status of this PR? I think it would be good to do this given the recent evidence we've had of external people actually using this repository. I do care about the comment I left being addressed before this goes in, though.

2022-11-22 17:28 UTC, ghartnett commented on README.md
> +Since 6.0, the legacy "mongo" shell has been replaced with "mongosh" which does not support benchRun(). To run this micro benchmark with MongoDB 6.0 you'll also need to download the 5.0 legacy "mongo
I'm concerned that more detailed instructions might be brittle and break in future. If you can suggest specific wording that would not be brittle I'll happily add it.

2022-11-22 17:36 UTC, ghartnett commented
@dstorch simple unsupported note added near the top. Please let me know if it works for you.

2022-11-29 21:47 UTC, dstorch approved these changes
Thanks @ghartnett! This LGTM now. I left a couple additional suggestions which I think are improvements, but I don't need to re-review the resulting changes.

2022-12-02 11:27 UTC, ghartnett commented on README.md
> +Since 6.0, the legacy "mongo" shell has been replaced with "mongosh" which does not support benchRun(). To run this micro benchmark with MongoDB 6.0 you'll also need to download the 5.0 legacy "mongo
Done

2022-12-02 11:27 UTC, merged