PERF-3569 Add more realistic scan test cases
mongodb/mongo-perf pull request #117
Opened 2022-12-13 17:23 UTC by lriuui0x0

2022-12-13 20:05 UTC, mtandrei requested changes
Thanks for picking this up Rui! I have two comments and this should be good to go.

2022-12-13 20:05 UTC, mtandrei commented on testcases/simple_query.js
> +        nDocs: 100,
Note that we already have such a test case that has a small number of documents: https://github.com/mongodb/mongo-perf/blob/fbc29ee5b451ca73268a9207d55e47f74af74eb9/testcases/simple_query.js#L168-L184

I would say, we want test cases with 10k and 100k documents and then pick either the smallDoc/largeDoc document generators. So, 2 test cases in total. In other words, I don't think we want to test empty documents since they aren't "realistic"

2022-12-14 11:18 UTC, lriuui0x0 commented on testcases/simple_query.js
> +        nDocs: 100,
Thanks I have updated the code.

2022-12-14 11:18 UTC, lriuui0x0 commented on testcases/simple_query.js
> +    /**
Thanks I have changed this.

2022-12-14 19:55 UTC, mtandrei approved these changes
LGTM Rui with an optional suggestion; thanks!

2022-12-14 19:55 UTC, mtandrei commented on testcases/simple_query.js
> +    /**
Thanks; looks good!

2022-12-14 19:55 UTC, mtandrei commented on testcases/simple_query.js
> +        nDocs: 10000,
[optional] consider generating these two in a loop like so: 

https://github.com/mongodb/mongo-perf/blob/97e50f99585e0c7bd80c065d9ec9a97dc2579f50/testcases/simple_sort_queries.js#L230-L233

2022-12-15 13:08 UTC, lriuui0x0 commented on testcases/simple_query.js
> +        nDocs: 10000,
Thanks for the tip, done!

2022-12-15 13:08 UTC, lriuui0x0 commented
evergreen merge

2022-12-15 13:08 UTC, merged