PERF-2636 Parameterize exact topN microbenchmarks with various values…
mongodb/mongo-perf pull request #91
Opened 2021-11-17 17:52 UTC by mtandrei

… for 'n' and group/partition/array size

Evergreen: https://spruce.mongodb.com/version/61953ddd5623430ed8611642/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

This patch changes the Exact TopN microbenchmarks to be parameterized by different values of 'n' and group/partition/array size depending in which context the different operators are being used in.

This patch shouldn't be too controversial, but there are big two questions at play:

- Which dimensions should we parameterize? I went with 'n' and group size, but maybe there are others which we might care about
- How many different values should we have for each dimension? Ideally, we can have as many as possible, but I realize that at a practical level, we don't want to generate a boatload of separate perf test cases (if we have d dimensions and 'n' measurements and 't' test cases, we will have t * (d^n) test cases. if d = n = 3, this means that for each test case, we would generate 27 distinct microbenchmarks!). In this patch, I went with d = n = 2, so we only get 4 per test case.

2021-11-29 22:28 UTC, dalyd reviewed
I started looking and had a couple of questions. I'll get a more thorough review tomorrow.

2021-11-29 22:28 UTC, dalyd commented on testcases/pipelines.js
> + * @param {Number} groupSize - The number of documents in each group in our test case.
Is this really the group size or rather the number of groups?

2021-11-29 22:28 UTC, dalyd commented on testcases/pipelines.js
> +        // inserts to the accumulators internal container, similar to Group.TenGroupsWithMaxN
Did MaxN change to TopN?

2021-11-30 14:12 UTC, mtandrei reviewed
Thanks for taking a look Dave! I've responded to your initial questions.

2021-11-30 14:12 UTC, mtandrei commented on testcases/pipelines.js
> + * @param {Number} groupSize - The number of documents in each group in our test case.
This is the group size; given that i is increasing, the formula used on line 330 will ensure values of i from 0 through groupSize - 1 will have the same groupKey of 0, i values from groupSize through (2 * groupSize) - 1 will have a groupKey of 1, and so on.

2021-11-30 14:12 UTC, mtandrei commented on testcases/pipelines.js
> +        // inserts to the accumulators internal container, similar to Group.TenGroupsWithMaxN
No, MaxN and TopN (and MinN and Bottom/BottomN, respectively) are different sets of operators. Whereas minN/maxN sort based on the input values, top/topN/bottom/bottomN allow you to specify a sort pattern (here's the [scope with more detail](https://docs.google.com/document/d/1wd04Di9d-Y0yoT2WUfb94zeQd_2zSBzrsg8v2oOOWd4/edit#heading=h.haavpvf17xzz)).

2021-12-01 22:10 UTC, dalyd commented on testcases/pipelines.js
> + * @param {Number} groupSize - The number of documents in each group in our test case.
I misread the math on line 330. That's on me -- sorry about that.

2021-12-01 22:12 UTC, dalyd commented on testcases/pipelines.js
> +        // inserts to the accumulators internal container, similar to Group.TenGroupsWithMaxN
Is the Group.TenGroupsWithMaxN test still being generated somewhere? Looking at this diff it looks like it went away.

2021-12-01 22:37 UTC, dalyd commented
Heh -- I didn't get there today -- sorry. Will try again tomorrow. Is @ksuarz planning to review? I wonder if it's worth waiting for his review first to make sure you are testing what you want.

2021-12-02 14:59 UTC, mtandrei commented on testcases/pipelines.js
> +        // inserts to the accumulators internal container, similar to Group.TenGroupsWithMaxN
Yes. Not only does this patch rename the test case itself (i.e. "Group.Min" + n + "With" + nDocs + "DocsAndGroupsOfSize" + groupSize), but the number of documents is now 10k (formerly 1000). 

If you want, I can modify the patch to continue generating the test cases that were being run before.

2021-12-02 21:22 UTC, ksuarz requested changes
I only have a few minor comments.

Do you have a patch build that shows the total execution time of the overall task? It would be good to compare that time with the baseline, to make sure these new test cases aren't pushing up the total time too much, or we should split into a new task.

2021-12-02 21:22 UTC, ksuarz commented on testcases/pipelines.js
> +                        _id: "$game", leaderBoard: {
Is this auto-formatted? If not, it would be nice to newline after `"$game"` so that `leaderBoard` gets its own line.

2021-12-02 21:22 UTC, ksuarz commented on testcases/pipelines.js
> +                        _id: "$game", leaderBoard: {
I have a similar comment for some of the other documents below, too. In general I like the usual C++ style of "all the parameters/key-values are on one line, or they get split into independent lines". But I acknowledge that it might not be possible here?

2021-12-03 15:00 UTC, dalyd reviewed
This is a pretty big change, and seems to be two things: 1. a refactor and 2. Adding new tests. Would it make sense to split those into two separate PRs and commits? That's a question, not a request. I was thinking it might make it easier to understand also if anyone goes looking at the commit history later. 

I took a quick look at the patch build. Assuming it is up to date and representative, all of the tasks are below 70 minutes, which seems fine. I don't think we need to split up the tasks for those reasons. 

It looks like all of the results are in the thousand of ops per second. Do I have that right? There's a lot of data so I'd like to double check that someone as looked at it and that I'm looking at the right thing.

2021-12-03 19:11 UTC, mtandrei reviewed
Thanks for taking a look Dave and Kyle; I know this is a substantial change so it is really appreciated!

With regards to splitting up the commit, I think it would be good to make the change easier to understand, but I’m not sure whether it’s worth it to go through interactive rebase to split the commit into 2. Instead, I can merge this with a detailed commit message (this should make it easier for anyone who’s interested in the commit history to understand what this commit does). How does the below sound?

PERF-2636 Add new $firstN/$topN workloads and parameterize exact topN microbenchmarks with various values for 'n' and group/partition/array size
 
This commit introduces two changes:
- Adds two new exact topN microbenchmarks, GamesSortIndexedFirstN and GamesUnindexedTopN, both of which are meant to compare the performance of an example use case for the exact topN operators.
- A refactor of the exact topN microbenchmarks such that they are now parameterized by different values of ‘n’ and  and group/partition/array size. This generates ~4 times the number of test cases and allows us to see how the performance of these operators changes as the different parameters’ values change.

Regarding the comment about time, the time it takes for ‘[aggregation_read_commands](https://spruce.mongodb.com/task/performance_linux_wt_standalone_all_feature_flags_aggregation_read_commands_patch_3e90750648f198504586b71000e8e0b526516392_61953ddd5623430ed8611642_21_11_17_17_38_34/tests?execution=0&sortBy=STATUS&sortDir=ASC)’ and ‘[views-aggregation](https://spruce.mongodb.com/task/performance_linux_wt_standalone_all_feature_flags_views_aggregation_patch_3e90750648f198504586b71000e8e0b526516392_61953ddd5623430ed8611642_21_11_17_17_38_34/tests?execution=0&sortBy=STATUS&sortDir=ASC
)’ combined take about 2 hours.
 
Finally, at the time of the latest patch build, the results are in the thousands of ops per second _only_ in the regular build variant (that is, in the non ‘all feature flags’ enabled BV). If you look at the [all feature flag results,](https://spruce.mongodb.com/version/61953ddd5623430ed8611642/tasks?page=0&variant=%5Elinux-wt-standalone-all-feature-flags%24) the performance of these operators vary somewhere between 10 ops/second to 300 ops/second depending on the test case ([see the following view for more info](https://evergreen.mongodb.com/task/performance_linux_wt_standalone_all_feature_flags_aggregation_read_commands_patch_3e90750648f198504586b71000e8e0b526516392_61953ddd5623430ed8611642_21_11_17_17_38_34##comparehashes=3e90750648f198504586b71000e8e0b526516392&threads=maxonly&selected.Aggregation.Empty=MAX&selected.Aggregation.GeoNear2d=MAX&selected.Aggregation.GeoNear2dSphere=MAX&selected.Aggregation.Group.All=MAX&selected.Aggregation.Group.TenGroups=MAX&selected.Aggregation.Group.TenGroupsWithAvg=MAX&selected.Aggregation.Group.GamesSortIndexedFirst10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.GamesTop10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Min10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Max10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.SetWindowFields.Min10With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.SetWindowFields.Max10With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.Group.First10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Last10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.SetWindowFields.First10With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.SetWindowFields.Last10With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.Group.GroupsWithTopNWithNVal10AndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomNWithNVal10AndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GamesSortIndexedFirst50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.GamesTop50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Min50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Max50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.SetWindowFields.Min50With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.SetWindowFields.Max50With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.Group.First50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Last50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.SetWindowFields.First50With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.SetWindowFields.Last50With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.Group.GroupsWithTopNWithNVal50AndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomNWithNVal50AndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GroupsWithTopAndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomAndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GamesSortIndexedFirst10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.GamesTop10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Min10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Max10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.SetWindowFields.Min10With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.SetWindowFields.Max10With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.Group.First10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Last10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.SetWindowFields.First10With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.SetWindowFields.Last10With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.Group.GroupsWithTopNWithNVal10AndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomNWithNVal10AndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GamesSortIndexedFirst50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.GamesTop50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Min50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Max50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.SetWindowFields.Min50With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.SetWindowFields.Max50With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.Group.First50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Last50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.SetWindowFields.First50With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.SetWindowFields.Last50With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.Group.GroupsWithTopNWithNVal50AndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomNWithNVal50AndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GroupsWithTopAndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomAndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Project.Min10WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Max10WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.First10WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Last10WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Min50WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Max50WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.First50WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Last50WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Min10WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Max10WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.First10WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Last10WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Min50WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Max50WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.First50WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Last50W [...]

2021-12-03 19:27 UTC, dalyd commented
>

2021-12-03 19:29 UTC, dalyd commented
> Finally, at the time of the latest patch build, the results are in the thousands of ops per second _only_ in the regular build variant (that is, in the non ‘all feature flags’ enabled BV). If you look at the [all feature flag results,](https://spruce.mongodb.com/version/61953ddd5623430ed8611642/tasks?page=0&variant=%5Elinux-wt-standalone-all-feature-flags%24) the performance of these operators vary somewhere between 10 ops/second to 300 ops/second depending on the test case ([see the following view for more info](https://evergreen.mongodb.com/task/performance_linux_wt_standalone_all_feature_flags_aggregation_read_commands_patch_3e90750648f198504586b71000e8e0b526516392_61953ddd5623430ed8611642_21_11_17_17_38_34##comparehashes=3e90750648f198504586b71000e8e0b526516392&threads=maxonly&selected.Aggregation.Empty=MAX&selected.Aggregation.GeoNear2d=MAX&selected.Aggregation.GeoNear2dSphere=MAX&selected.Aggregation.Group.All=MAX&selected.Aggregation.Group.TenGroups=MAX&selected.Aggregation.Group.TenGroupsWithAvg=MAX&selected.Aggregation.Group.GamesSortIndexedFirst10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.GamesTop10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Min10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Max10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.SetWindowFields.Min10With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.SetWindowFields.Max10With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.Group.First10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Last10With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.SetWindowFields.First10With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.SetWindowFields.Last10With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.Group.GroupsWithTopNWithNVal10AndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomNWithNVal10AndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GamesSortIndexedFirst50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.GamesTop50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Min50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Max50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.SetWindowFields.Min50With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.SetWindowFields.Max50With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.Group.First50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.Group.Last50With10000DocsAndGroupsOfSize100=MAX&selected.Aggregation.SetWindowFields.First50With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.SetWindowFields.Last50With10000DocsAndPartitionsOfSize100=MAX&selected.Aggregation.Group.GroupsWithTopNWithNVal50AndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomNWithNVal50AndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GroupsWithTopAndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomAndGroupsOfSize100And10000Docs=MAX&selected.Aggregation.Group.GamesSortIndexedFirst10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.GamesTop10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Min10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Max10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.SetWindowFields.Min10With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.SetWindowFields.Max10With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.Group.First10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Last10With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.SetWindowFields.First10With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.SetWindowFields.Last10With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.Group.GroupsWithTopNWithNVal10AndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomNWithNVal10AndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GamesSortIndexedFirst50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.GamesTop50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Min50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Max50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.SetWindowFields.Min50With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.SetWindowFields.Max50With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.Group.First50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.Group.Last50With10000DocsAndGroupsOfSize250=MAX&selected.Aggregation.SetWindowFields.First50With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.SetWindowFields.Last50With10000DocsAndPartitionsOfSize250=MAX&selected.Aggregation.Group.GroupsWithTopNWithNVal50AndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomNWithNVal50AndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GroupsWithTopAndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Group.GroupsWithBottomAndGroupsOfSize250And10000Docs=MAX&selected.Aggregation.Project.Min10WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Max10WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.First10WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Last10WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Min50WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Max50WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.First50WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Last50WithArraysOfSize50Over1000Docs=MAX&selected.Aggregation.Project.Min10WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Max10WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.First10WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Last10WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Min50WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Max50WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.First50WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Last50WithArraysOfSize250Over1000Docs=MAX&selected.Aggregation.Project.Min10WithArraysOfSize500Over1000Docs=MAX&selected.Aggregation.Project.Max10WithArraysOfSize500Over1000Docs=MAX&selected.Aggregation.Project.First10WithArraysOfSize500Over1000Docs=MAX&selected.Aggregation.Project.Last10WithArraysOfSize500Over1000Docs=MAX&selected.Aggregation.Project.Min50WithArraysOfSize500Over1000Docs=MAX&selected.Aggregation.Project.Max50WithArraysOfSize500Over1000Docs=MAX&selected.Aggregation.Project.First50WithArraysOfSize500Over1000Docs=MAX&selected.Aggregation.Project.Last50WithArraysOfSize500Over1000Docs=MAX&selected.Aggregation.Group.OneFieldReferencedOutOfMany=MAX&selected.Aggregation.Limit=MAX&selected.Aggregation.Lookup=MAX&selected.Aggregation.Lookup.Pipeline=MAX&selected.Aggregation.Lookup.LocalArray=MAX&selected.Aggregation.Lookup.LocalArray.Pipeline=MAX&selected.Aggregation.Lookup.LocalArrayOfObject=MAX&selected.Aggregation.Lookup.LocalArrayOfObject.Pipeline=MAX&selected.Aggregation.Lookup.UncorrelatedJoin=MAX&selected.Aggregation.Lookup.UncorrelatedJoin.NoCache=MAX&selected.Aggregation.Lookup.UncorrelatedPrefixJoin=MAX&selected.Aggregation.Lookup.UncorrelatedPrefixJoin.NoCache=MAX&selected.Aggregation.LookupViaGraphLookup=MAX&selected.Aggregation.LookupOrders=MAX&selected.Aggregation.GraphLookupSocialite=MAX&selected.Aggregation.GraphLookupNeighbors=MAX&selected.Aggregation.Match=MAX&selected.Aggregation.MatchOneFieldFromBigDocument=MAX&selected.Aggregation.MatchManyFieldsFromBigDocument=MAX&selected.Aggregation.Project=MAX&selected.Aggregation.ExpressionObject=MAX&selected.Aggregation.Redact=MAX&selected.Aggregation.Sample.SmallSample=MAX&selected.Aggregation.Sample.LargeSample=MAX&selected.Aggregation.Skip=MAX&selected.Aggregation.Sort=MAX&selected.Aggregation.Unwind=MAX&selected.Aggregation.S [...]

2021-12-03 19:33 UTC, mtandrei commented
It's so much slower on the feature flag branch because on the non feature flag branch, the queries aren't actually running (that is, instead of performing the actual work and running, the queries error at parse time). In other words, the queries themselves require that the feature flag is enabled for them to work properly.

2021-12-03 20:40 UTC, dalyd commented
> It's so much slower on the feature flag branch because on the non feature flag branch, the queries aren't actually running (that is, instead of performing the actual work and running, the queries error at parse time). In other words, the queries themselves require that the feature flag is enabled for them to work properly.

I was wondering if that was the case. Okay. We're probably okay regardless. LGTM for my part.

2021-12-03 20:41 UTC, dalyd approved these changes

2021-12-14 20:52 UTC, ksuarz commented on testcases/pipelines.js
> +                        n ? {n} : {}, // topN and bottomN also need an extra n parameter.
🤦

2021-12-15 20:06 UTC, mtandrei commented
Thanks for the review, Dave and Kyle! Going to go ahead and merge this one following https://evergreen.mongodb.com/version/61ba0cd7850e61347667b873

2021-12-15 20:07 UTC, merged