PERF-2588 Add performance tests for $sortArray
mongodb/mongo-perf pull request #92
Opened 2021-12-02 03:24 UTC by dobroshynski

Performance microbenchmarks for new $sortArray expression being added in PM-2552

2021-12-02 20:17 UTC, mtandrei requested changes
This looks good; nice work Andrii! Minor comments only and a couple of questions.

2021-12-02 20:17 UTC, mtandrei commented on testcases/pipelines.js
> + * the array with elements in descending order or ascending order to maximizes the number of
[nit] s/maximizes/maximize

2021-12-02 20:17 UTC, mtandrei commented on testcases/pipelines.js
> + * @param {String} variant: controls what data the array holds - either 'numbers', 'strings',
[nit] instead of 'controls what data', how about 'controls the type of data that the array holds'?

2021-12-02 20:17 UTC, mtandrei commented on testcases/pipelines.js
> + * $sortArray aggregation expression. Depending on the sort direction, we specifically generate
[nit] s/the performance of $sortArray/the performance of the $sortArray

2021-12-02 20:17 UTC, mtandrei commented on testcases/pipelines.js
> +    for(let idx = 0; idx < numElements; ++idx){
suggest pulling out `isDescending ? -idx : idx` from lines 2461, 2463, 2466 out of the if else block, assigning it to a variable and then using it on those lines. Something like 
`const val = isDescending ? -idx : idx;
...
arr.push(val);
...
arr.push(val.toString);`

and so on

2021-12-02 20:17 UTC, mtandrei commented on testcases/pipelines.js
> +        generateTestCase({
[optional] I guess we're sticking with the default number of documents (I think it's 500?) because the number of documents doesn't matter, rather, the number of elements per array does, right?

2021-12-03 15:21 UTC, dalyd reviewed
Not much from me. It looks good and it looks like Mihai has a good handle on the details. 

Could you run a patch build and link it to the PR? Also, could you list out the new test names and matching tasks? I'd like to take a look at that once it's in.

2021-12-03 15:21 UTC, dalyd commented on testcases/pipelines.js
> +    [1, 10, 100, 1000].forEach(numElements => {
Are all 4 levels telling us something interesting? Fine for exploration, but if the answer is no, let's cut it down.

2021-12-03 15:25 UTC, ksuarz commented on testcases/pipelines.js
> +    [1, 10, 100, 1000].forEach(numElements => {
How about sticking to 10, 100 and 1000?

2021-12-03 18:35 UTC, dobroshynski commented on testcases/pipelines.js
> +    [1, 10, 100, 1000].forEach(numElements => {
This sounds good, I trimmed it down to just 10, 100, 1000

2021-12-03 18:35 UTC, dobroshynski commented on testcases/pipelines.js
> + * the array with elements in descending order or ascending order to maximizes the number of
Done

2021-12-03 18:35 UTC, dobroshynski commented on testcases/pipelines.js
> + * @param {String} variant: controls what data the array holds - either 'numbers', 'strings',
Done

2021-12-03 18:35 UTC, dobroshynski commented on testcases/pipelines.js
> + * $sortArray aggregation expression. Depending on the sort direction, we specifically generate
Done

2021-12-03 18:36 UTC, dobroshynski commented on testcases/pipelines.js
> +    for(let idx = 0; idx < numElements; ++idx){
Done!

2021-12-03 18:36 UTC, dobroshynski commented on testcases/pipelines.js
> +        generateTestCase({
Yep I think that's exactly the idea, hence I left it blank to stick with the default 500

2021-12-03 18:38 UTC, dobroshynski commented
Thanks a lot for taking a look Mihai & David! Made all the suggested edits and kicked off a patch build [here](https://spruce.mongodb.com/version/61aa62b7562343496401357b/changes). I configured it with a diff to `dsi` to include the feature flag for this expression in that variant, so I hope that should work

2021-12-13 23:17 UTC, dobroshynski commented
hey team! now that skunkworks is done, would appreciate a re-review, thanks!

2021-12-14 16:21 UTC, mtandrei approved these changes
LGTM mod a couple last nits; nice work Andrii!

This patch generates 30 test cases, but I think that should be ok given that the run time for a task doesn't go up by that much (I will let Dave determine whether this is acceptable).

2021-12-14 16:21 UTC, mtandrei commented on testcases/pipelines.js
> +    for(let idx = 0; idx < numElements; ++idx){
nice; is 'arrVal' declared with 'let' because of line 2464? otherwise, recommend making this const.

2021-12-14 16:21 UTC, mtandrei commented on testcases/pipelines.js
> +    return base + "_" + numElements.toString() + "_" + dirString;
[question] do other workloads in the microbenchmarks use the underscore convention? If no, recommend deleting them.

2021-12-14 20:58 UTC, ksuarz commented on testcases/pipelines.js
> +    return base + "_" + numElements.toString() + "_" + dirString;
I think we prefer dots?

2021-12-15 15:00 UTC, dobroshynski commented on testcases/pipelines.js
> + * @param {String} variant: controls what data the array holds - either 'numbers', 'strings',
Pretty sure I pushed the change just this thing is outdated?

2021-12-15 15:01 UTC, dobroshynski commented on testcases/pipelines.js
> +    return base + "_" + numElements.toString() + "_" + dirString;
I see `Group.SumAccTopField_SingleIndex_LowSelectivityMatch_LL` and `SumAccTopField_SingleIndex_LL` and more above in the file

2021-12-15 19:51 UTC, dalyd commented
> hey david, thanks for the response. I'm not sure I totally follow about the `aggregation_read_commands` taking longer in waterfall than here, it looked to me like everything ran as expected, though since this is my first performance related task, perhaps I am forgetting something. Regarding tests and the number, I did not see < 1 ops/s but perhaps then we can get rid of the `1000` "level" since as you pointed out the levels don't really tell anything particularly interesting. and even with just 10, 100 there should be enough tests given that the code generates sorts for strings, numbers, and objects

I may be looking at the wrong things :) I was having a little bit of trouble figuring out which tasks to look at in your patch build. It looked like some of the new tests were in the aggregation_read_commands task. I'm in the office tomorrow, so the shortest path may be to look over someone's shoulder tomorrow (if someone else is in). 

In the meantime, here's the aggregation_read_commands task in your patch on all feature flags: https://spruce.mongodb.com/task/performance_linux_wt_standalone_all_feature_flags_aggregation_read_commands_patch_c379649913d701e406bec73b51a85ea6b618f677_61aa62b7562343496401357b_21_12_03_18_34_18/tests?execution=0&sortBy=STATUS&sortDir=ASC

Ah phooey -- human error on my part on the times. I see now I must have looked at the wrong task for comparison (agg-query-comparison-read-commands, rather than aggregation-read-commands). Sorry about that bit. 

I do still see Aggregation.Project.SortArray_ObjectArray_1000_Asc reporting 0.4636431077758186 as a result. So, that's one case less than 1. It is the 1000 level. What do Kyle and Mihai think about that one.

2021-12-15 19:54 UTC, ksuarz commented on testcases/pipelines.js
> +    return base + "_" + numElements.toString() + "_" + dirString;
🤷

2021-12-15 19:58 UTC, ksuarz commented
@dalyd, @dobroshynski -- it is a little sad that the perf is kind of slow that a 1k array can't be sorted... but I also think it's a bit of an extreme case. I'd be okay with dropping it?

The next slowest after the 1k array is `Aggregation.Project.SortArray_ObjectArray_100_Desc`, which is at 6.914469750161532. I'm assuming that's in the stable zone?

2021-12-15 20:13 UTC, dalyd commented
@ksuarz that sounds fine to me.

2021-12-15 20:37 UTC, ksuarz approved these changes
Based on the latest exchange, this LGTM mod getting rid of the 1k sort case.

2021-12-20 17:23 UTC, dobroshynski commented
thanks for the review & comments all. @dalyd  David if you do not have any further objections / requests I will merge this in

2021-12-20 20:00 UTC, dalyd approved these changes

2021-12-20 21:23 UTC, merged